spring:
  application:
    name: zuul-server

server:
  port: 8090

logging:
  level:
    com:
      shiro: debug
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p})  %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

#configure eureka access point
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

#configure zuul's routes
zuul:
  routes:
    product:
      service-id: product-service
      path: /api/product/**  #we map the path of products
    item:
      service-id: item-service
      path: /api/item/**   #we map the path of items

#configure time out

hystrix:
  command:
    default:
      execution:
        isolation:
          theard:
            timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000

